export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CHOOSEN_CATEGORY_REQUEST = 'FETCH_CHOOSEN_CATEGORY_REQUEST';
export const FETCH_CHOOSEN_CATEGORY_SUCCESS = 'FETCH_CHOOSEN_CATEGORY_SUCCESS';

export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_LOAD_MORE = 'FETCH_LOAD_MORE';

export const ADD_SEARCH_TEXT = 'ADD_SEARCH_TEXT'; 
export const FETCH_SEARCH_TEXT = 'FETCH_SEARCH_TEXT';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const ADD_ITEM_SIZE = 'ADD_ITEM_SIZE';
export const DELETE_ITEM_SIZE = 'DELETE_ITEM_SIZE';
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY';

export const INIT_ORDER = 'INIT_ORDER';
export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const ADD_ORDER_PHONE = 'ADD_ORDER_PHONE';
export const ADD_ORDER_ADDRESS = 'ADD_ORDER_ADDRESS';
export const ADD_ORDER_AGREEMENT = 'ADD_ORDER_AGREEMENT';

export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_SUM = 'GET_CART_SUM';
export const CART_FAILURE = 'CART_FAILURE';
export const CART_SUCCESS = 'CART_SUCCESS';

export const CLEAR_STORAGE = 'CLEAR_STORAGE';
export const SET_ITEM_STORAGE = 'SET_ITEM_STORAGE';
export const GET_ITEM_STORAGE = 'GET_ITEM_STORAGE';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';